### PR TITLE
Couple improvements to fifo plugin

### PR DESCRIPTION
**Pull request by bacher09**
Original code of fifo plugin have couple issues. First of all, it is using polling with 0.2 seconds interval for checking or FIFO available for read. For one channel it will produce 5 system calls (1 / 0.2) per second. It looks like small amount of work, but let's imagine that bot joins to 19 channels. This means that it will execute 100 system calls per second (19 channels + 1 for :raw, 20 * 5 = 100). More channels will cause more load. Instead of polling I'm using event driven approach, handler are called only when new data available in fifo.

There are also another issue, POSIX recommends using  `O_NONBLOCK` over `O_NDELAY`. Here's one of explanations [why](https://mail.python.org/pipermail/python-list/1999-May/013687.html). Same recommendations came from  [Richard Stevens book](https://en.wikipedia.org/wiki/Advanced_Programming_in_the_Unix_Environment).

Another thing, that is handled in different way in my version, is handling of partial input. Python's `readline` isn't designed for non-blocking files and because of this it isn't handles partial input. For example:
```bash
    #!/bin/bash
    echo -n "t" > /tmp/irc3/channel
    echo -n "e" > /tmp/irc3/channel
    echo -n "s" > /tmp/irc3/channel
    echo "t" > /tmp/irc3/channel
```
or similar python code
```python
    #!/bin/env python
    # should be opened without buffering
    with open("/tmp/irc3/channel", "wb", 0) as f:
        for char in b"test\n":
            f.write(bytes([char]))
```

This will send couple lines to IRC instead of one. My version will send only one line in this case, but this approach have some drawbacks too. Major drawback is that it requires saving input values to memory and can cause memory leaking in case of very large lines. To prevent this, I limited maximum size of line, if line are longer it just delivered to IRC without waiting other parts of line.

There are also one issue which I didn't fix here. Suppose bot joins two channels: `#python` and `##python`. They both will use same FIFO file. Most of file systems on *nix like OSs isn't restrict these symbols `#&+`. So, I think, it should be safe to remove `.strip('#&+')` from code. Also, [weechat logger](https://weechat.org/files/doc/stable/weechat_user.en.html#logger_filenames_masks) by default create files with these chars for channels.

### CODE REVIEW

**Comment by gawel** [comment]
Looks great. My only problem is that I have to keep at least py3.4 compat as we use this plugin on a debian jessie (and don't want to compile a python binary because of my BOFHs). Do you think you can handle both case ? eg: run different code regarding the python version ?
If it's a real problem, I can tag the next release as the latest py3.4 compatible version, but I'd like to avoid that.

**Comment by gawel** [comment]
Oh, looks like I missread the code! The compat is still there. Can you confirm that ?

**Comment by bacher09** [comment]
It should work under 3.4 and 3.3 too. But today I found another issue in my version. Looks like trick with opening FIFO in `O_RDWR` mode works only in Linux. For example here's quote from OpenBSD [man open](http://man.openbsd.org/?query=open&apropos=0&sec=0&arch=default&manpath=OpenBSD-current):

> A FIFO should either be opened with O_RDONLY or with O_WRONLY. The behavior for opening a FIFO with O_RDWR is undefined.

And portable way to handle this is reopen FIFO each time when writer process closed it.
For more info refer to [this link](http://stackoverflow.com/questions/15055065/o-rdwr-on-named-pipes-with-poll).

**Comment by bacher09** [comment]
Later I will update this pull request in more portable way.  I'm going to test it under OpenBSD and maybe some other *nix like systems.

**Pull request merged**
