### PR TITLE
Allow to hide commands from !help

### PR DESCRIPTION
**Pull request by thomwiggers**
Because sometimes you don't want your average user to start trying out !quit (even though he will probably not be able to run it).

### CODE REVIEW

**Comment by gawel** [comment]
That's great. Except that I'm not a huge fan of the option name. Why not just hidden=True or secret=True ?

**Comment by thomwiggers** [comment]
I considered 'secret', but it's not like `!help mysecretcommand` won't still work (and that's ok imo). I also felt `hidden` or `secret` may be a bit ambiguous, so I went with the really obvious name.

**Comment by gawel** [comment]
Yes, obvious_and_very_long :) Let say it's ok

**Comment by thomwiggers** [comment]
Ap least you don't need to type it 10 times per function :-p

**Pull request merged**
