### PR TITLE
irc3d fixes

### PR DESCRIPTION
**Pull request by mickael9**
This fixes several issues with irc3d

### CODE REVIEW

**Comment by mickael9** [comment]
Dear god that thing is annoying, hopefully I'm done now :smile:

**Comment by gawel** [comment]
Yep, it's a bit noisy... Thanks for the patches by the way

**Comment by mickael9** [comment]
Looks like you can disable them and use the new status API: https://github.com/lemurheavy/coveralls-public/issues/25#issuecomment-72534212

**Comment by gawel** [comment]
Settings updated. Thanks

**Pull request merged**
